### ISSUE TITLE
Excepcion al hacer connect a torneo

### ISSUE THREAD

**Issue by SrHeli0s** [UNIZAR-30226-2022-07/Deploy#10]
No se muy bien porque pasa

    2022-05-21T07:13:54.878873+00:00 app[web.1]: Exception in thread "clientInboundChannel-3" org.springframework.messaging.MessageDeliveryException: Failed to handle GenericMessage [payload=byte[2], headers={simpMessageType=MESSAGE, stompCommand=SEND, nativeHeaders={Authorization=[Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJIZWxpb3MyIiwiaWF0IjoxNjUzMTE3MjMxLCJleHAiOjE2NTMyMDM2MzF9.4xY6QOXYtezGgfggz5zEsYCbvOqkwWVZ1fGZ410IrbtlDjUQ0BVdPEy6DL3oDFLJPhDylmnj0IVr7LqJhlHRNQ], username=[Helios2], destination=[/game/connect/torneo/dfe062d2-fbc6-4729-a689-41bc271cd7f8], content-length=[2]}, simpSessionAttributes={}, simpHeartbeat=[J@8a0aaab, simpSessionId=chxfp3jz, simpDestination=/game/connect/torneo/dfe062d2-fbc6-4729-a689-41bc271cd7f8}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@f931bc1 in WebSocketAnnotationMethodMessageHandler[prefixes=[/game/]]; nested exception is java.lang.IllegalStateException: No exception types mapped to public void com.cerea_p1.spring.jpa.postgresql.controller.TorneoController.begin(java.lang.String,java.lang.String), failedMessage=GenericMessage [payload=byte[2], headers={simpMessageType=MESSAGE, stompCommand=SEND, nativeHeaders={Authorization=[Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJIZWxpb3MyIiwiaWF0IjoxNjUzMTE3MjMxLCJleHAiOjE2NTMyMDM2MzF9.4xY6QOXYtezGgfggz5zEsYCbvOqkwWVZ1fGZ410IrbtlDjUQ0BVdPEy6DL3oDFLJPhDylmnj0IVr7LqJhlHRNQ], username=[Helios2], destination=[/game/connect/torneo/dfe062d2-fbc6-4729-a689-41bc271cd7f8], content-length=[2]}, simpSessionAttributes={}, simpHeartbeat=[J@8a0aaab, simpSessionId=chxfp3jz, simpDestination=/game/connect/torneo/dfe062d2-fbc6-4729-a689-41bc271cd7f8}]
    2022-05-21T07:13:54.879025+00:00 app[web.1]: 	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153)
    2022-05-21T07:13:54.879093+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    2022-05-21T07:13:54.879152+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    2022-05-21T07:13:54.879193+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:750)
    2022-05-21T07:13:54.879474+00:00 app[web.1]: Caused by: java.lang.IllegalStateException: No exception types mapped to public void com.cerea_p1.spring.jpa.postgresql.controller.TorneoController.begin(java.lang.String,java.lang.String)
    2022-05-21T07:13:54.879552+00:00 app[web.1]: 	at org.springframework.messaging.handler.invocation.AbstractExceptionHandlerMethodResolver.getExceptionsFromMethodSignature(AbstractExceptionHandlerMethodResolver.java:82)
    2022-05-21T07:13:54.879620+00:00 app[web.1]: 	at org.springframework.messaging.handler.annotation.support.AnnotationExceptionHandlerMethodResolver.initExceptionMappings(AnnotationExceptionHandlerMethodResolver.java:61)
    2022-05-21T07:13:54.879673+00:00 app[web.1]: 	at org.springframework.messaging.handler.annotation.support.AnnotationExceptionHandlerMethodResolver.<init>(AnnotationExceptionHandlerMethodResolver.java:48)
    2022-05-21T07:13:54.879737+00:00 app[web.1]: 	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.createExceptionHandlerMethodResolverFor(SimpAnnotationMethodMessageHandler.java:520)
    2022-05-21T07:13:54.879799+00:00 app[web.1]: 	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.getExceptionHandlerMethod(AbstractMethodMessageHandler.java:640)
    2022-05-21T07:13:54.879885+00:00 app[web.1]: 	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.processHandlerMethodException(AbstractMethodMessageHandler.java:595)
    2022-05-21T07:13:54.879951+00:00 app[web.1]: 	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:585)
    2022-05-21T07:13:54.880017+00:00 app[web.1]: 	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511)
    2022-05-21T07:13:54.880063+00:00 app[web.1]: 	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94)
    2022-05-21T07:13:54.880137+00:00 app[web.1]: 	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:524)
    2022-05-21T07:13:54.880205+00:00 app[web.1]: 	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:458)
    2022-05-21T07:13:54.880287+00:00 app[web.1]: 	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
    2022-05-21T07:13:54.880354+00:00 app[web.1]: 	... 3 more
    2022-05-21T07:14:25.470041+00:00 app[web.1]: 2022-05-21 07:14:25.469  INFO 4 --- [MessageBroker-4] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[2 current WS(2)-HttpStream(0)-HttpPoll(0), 2 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(2)-CONNECTED(2)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 16, active threads = 0, queued tasks = 0, completed tasks = 21], outboundChannel[pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2], sockJsScheduler[pool size = 8, active threads = 1, queued tasks = 3, completed tasks = 11]

**Comment by SrHeli0s** [comment]
Podeis usar fweb para generarlo:
1. Crear un nuevo torneo desde una cuenta
2. Intentar unirse desde otra
