### ISSUE TITLE
null pointer exception en getMano

### ISSUE THREAD

**Issue by SrHeli0s** [UNIZAR-30226-2022-07/Deploy#13]
Cuando ejecuto getMano salta un null pointer exception:

    2022-05-21T17:32:59.962078+00:00 app[web.1]: java.lang.NullPointerException: null
    2022-05-21T17:32:59.962079+00:00 app[web.1]: 	at com.cerea_p1.spring.jpa.postgresql.controller.GameController.getManoJugador(GameController.java:144) ~[classes!/:0.1.1-SNAPSHOT]
    2022-05-21T17:32:59.962080+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_332-heroku]
    2022-05-21T17:32:59.962080+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_332-heroku]
    2022-05-21T17:32:59.962087+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_332-heroku]
    2022-05-21T17:32:59.962088+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_332-heroku]
    2022-05-21T17:32:59.962088+00:00 app[web.1]: 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962089+00:00 app[web.1]: 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962089+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962090+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962090+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962090+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962091+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962091+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962091+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962092+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962092+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962092+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962092+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962092+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962093+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962093+00:00 app[web.1]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962093+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962093+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962093+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962093+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962094+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962094+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962095+00:00 app[web.1]: 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962101+00:00 app[web.1]: 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962101+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962101+00:00 app[web.1]: 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962102+00:00 app[web.1]: 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962102+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962102+00:00 app[web.1]: 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962102+00:00 app[web.1]: 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962102+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962103+00:00 app[web.1]: 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962103+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962103+00:00 app[web.1]: 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962103+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962103+00:00 app[web.1]: 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962103+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962104+00:00 app[web.1]: 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:150) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962104+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962104+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962104+00:00 app[web.1]: 	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962104+00:00 app[web.1]: 	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962104+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962105+00:00 app[web.1]: 	at com.cerea_p1.spring.jpa.postgresql.security.jwt.AuthTokenFilter.doFilterInternal(AuthTokenFilter.java:45) ~[classes!/:0.1.1-SNAPSHOT]
    2022-05-21T17:32:59.962105+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962110+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962110+00:00 app[web.1]: 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962111+00:00 app[web.1]: 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962111+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962111+00:00 app[web.1]: 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962114+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962115+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962115+00:00 app[web.1]: 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962115+00:00 app[web.1]: 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962115+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962115+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962116+00:00 app[web.1]: 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962116+00:00 app[web.1]: 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962116+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962116+00:00 app[web.1]: 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962117+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962117+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962117+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962117+00:00 app[web.1]: 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.6.2.jar!/:5.6.2]
    2022-05-21T17:32:59.962117+00:00 app[web.1]: 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962118+00:00 app[web.1]: 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962118+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962118+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962118+00:00 app[web.1]: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962119+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962119+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962119+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962119+00:00 app[web.1]: 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962120+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962120+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962120+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962120+00:00 app[web.1]: 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962120+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.17.jar!/:5.3.17]
    2022-05-21T17:32:59.962123+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962123+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962123+00:00 app[web.1]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962123+00:00 app[web.1]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962123+00:00 app[web.1]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962124+00:00 app[web.1]: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962125+00:00 app[web.1]: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962125+00:00 app[web.1]: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962125+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962125+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962125+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.60.jar!/:na]
    2022-05-21T17:32:59.962126+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_332-heroku]
    2022-05-21T17:32:59.962126+00:00 app[web.1]: 
    2022-05-21T17:33:04.481194+00:00 heroku[router]: at=info method=POST path="/server/pasarTurno" host=onep1.herokuapp.com request_id=f50a6043-faa3-4e79-9b06-ccd4d458edac fwd="54.195.136.199" dyno=web.1 connect=0ms service=12ms status=200 bytes=470 protocol=https
    2022-05-21T17:33:04.181160+00:00 app[web.1]: [Content-Type: text/plain; charset=ISO-8859-1,Content-Length: 70,Chunked: false]
    2022-05-21T17:33:04.472872+00:00 app[web.1]: 2022-05-21 17:33:04.472  INFO 4 --- [io-48232-exec-1] MyLog                                    : Ha llegado el método del server
    2022-05-21T17:33:16.561198+00:00 heroku[router]: at=info method=POST path="/server/pasarTurno" host=onep1.herokuapp.com request_id=8617a6eb-0957-478b-9c61-3a5a0e10b5b8 fwd="54.195.136.199" dyno=web.1 connect=0ms service=9ms status=200 bytes=470 protocol=https
    2022-05-21T17:33:16.474656+00:00 app[web.1]: [Content-Type: text/plain; charset=ISO-8859-1,Content-Length: 70,Chunked: false]
    2022-05-21T17:33:16.557077+00:00 app[web.1]: 2022-05-21 17:33:16.556  INFO 4 --- [io-48232-exec-3] MyLog                                    : Ha llegado el método del server
    2022-05-21T17:33:28.583614+00:00 heroku[router]: at=info method=POST path="/server/pasarTurno" host=onep1.herokuapp.com request_id=07ef1fa1-18dd-45c5-ae63-81c3ffbb2abe fwd="54.195.136.199" dyno=web.1 connect=0ms service=5ms status=200 bytes=470 protocol=https
    2022-05-21T17:33:28.558418+00:00 app[web.1]: [Content-Type: text/plain; charset=ISO-8859-1,Content-Length: 70,Chunked: false]
    2022-05-21T17:33:28.580680+00:00 app[web.1]: 2022-05-21 17:33:28.580  INFO 4 --- [io-48232-exec-4] MyLog                                    : Ha llegado el método del server

Ni idea de porque
Gracias :)

**Comment by nereagallego** [comment]
Mano del jugador null en la partida eb79f185-d159-45cc-af25-ecc84a042e0c
Me estáis pasando el nombre de un jugador nulo
